#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-scale "$HOME"/.config/background &
picom &
polybar -r &
flameshot &
dunst &
xsetroot -cursor_name left_ptr &
ulimit -n 4096

# xinput --> get desired id
# xinput list-props id --> get desired props
xinput set-prop 12 "libinput Disable While Typing Enabled" 0
xinput set-prop 12 "libinput Accel Speed" 0.35
setxkbmap -layout pc104

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width           0
bspc config window_gap             5

bspc config split_ratio            0.50
#bspc config borderless_monocle     true
bspc config gapless_monocle        true

bspc config top_padding            40

bspc config pointer_follows_focus  false
bspc config focus_follows_pointer  true


# Unblocking wifi (im lazy)
rfkill unblock all

betterlockscreen -u "$HOME"/.config/background
xss-lock -- betterlockscreen -l
